name: Deploy and Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
        BASEURL: ${{ secrets.BASEURL }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install -r requirements.txt

    - name: Wait for Render deployment to complete (5 minutes)
      run: sleep 300  # 5 minutes (300 seconds)

    - name: Run Selenium tests
      run: |
        pytest tests/selenium_script.py --maxfail=1 --disable-warnings -v
