name: Deploy and Run Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      BASEURL: ${{ secrets.BASEURL }}  # Set your environment URL as secret

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  

    - name: Set up Python
      uses: actions/setup-python@v3  
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install -r requirements.txt
    
    - name: Check Chrome version and download matching ChromeDriver
      run: |
        # Extract Chrome version
        CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+')
        echo "Detected Chrome version: $CHROME_VERSION"
        
        # Attempt to download ChromeDriver for the detected version, fall back to the latest version if not found
        CHROME_DRIVER_URL="https://chromedriver.storage.googleapis.com/$CHROME_VERSION/chromedriver_linux64.zip"
        wget -q "$CHROME_DRIVER_URL" -O chromedriver_linux64.zip || {
          echo "Specific ChromeDriver version not found, falling back to the latest release."
          wget -q "https://chromedriver.storage.googleapis.com/LATEST_RELEASE/chromedriver_linux64.zip" -O chromedriver_linux64.zip
        }
        
        # Unzip and set up ChromeDriver
        unzip chromedriver_linux64.zip -d /usr/local/bin/
        rm chromedriver_linux64.zip

    - name: Verify Python version
      run: python --version

    - name: Verify pip and installed packages
      run: |
        pip --version
        pip list

    - name: Verify virtual environment
      run: |
        source .venv/bin/activate
        which python
        which pip

    - name: Check if pytest is installed
      run: |
        source .venv/bin/activate
        pytest --version

    - name: Wait for Render deployment to complete (2 minutes)
      run: sleep 120

    - name: Run Selenium tests
      run: |
        source .venv/bin/activate
        pytest tests/selenium_script.py --maxfail=1 --disable-warnings -v
