name: Deploy and Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      BASEURL: ${{ secrets.BASEURL }}  # Set your environment URL as secret

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  

    - name: Set up Python
      uses: actions/setup-python@v3  
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install -r requirements.txt
    
    - name: Check Chrome version
      run: google-chrome --version
    
    - name: Install ChromeDriver
      run: |
        CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+')
        CHROME_DRIVER_VERSION=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION)
        wget https://chromedriver.storage.googleapis.com/${CHROME_DRIVER_VERSION}/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin

    - name: Verify Python version
      run: python --version

    - name: Verify pip and installed packages
      run: |
        pip --version
        pip list

    - name: Verify virtual environment
      run: |
        source .venv/bin/activate
        which python
        which pip

    - name: Check if pytest is installed
      run: |
        source .venv/bin/activate
        pytest --version

    - name: Wait for Render deployment to complete (2 minutes)
      run: sleep 120

    - name: Run Selenium tests
      run: |
        source .venv/bin/activate
        pytest tests/selenium_script.py --maxfail=1 --disable-warnings -v
