name: Deploy and Run Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      BASEURL: ${{ secrets.BASEURL }}  # Set your environment URL as secret

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  

    - name: Set up Python
      uses: actions/setup-python@v3  
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install -r requirements.txt
    
    - name: Check Chrome version
      id: chrome_version
      run: |
        CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+')
        echo "Chrome version: $CHROME_VERSION"
        echo "CHROME_VERSION=$CHROME_VERSION" >> $GITHUB_ENV

    - name: Install ChromeDriver
      run: |
        CHROME_DRIVER_VERSION=$(curl -sS "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${{ env.CHROME_VERSION }}" || echo "")
        if [ -z "$CHROME_DRIVER_VERSION" ]; then
          echo "Using the latest ChromeDriver version"
          CHROME_DRIVER_VERSION=$(curl -sS "https://chromedriver.storage.googleapis.com/LATEST_RELEASE")
        fi
        echo "Downloading ChromeDriver version $CHROME_DRIVER_VERSION"
        wget -q "https://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip"
        unzip chromedriver_linux64.zip -d /usr/local/bin/
        rm chromedriver_linux64.zip

    - name: Verify Python version
      run: python --version

    - name: Verify pip and installed packages
      run: |
        pip --version
        pip list

    - name: Verify virtual environment
      run: |
        source .venv/bin/activate
        which python
        which pip

    - name: Check if pytest is installed
      run: |
        source .venv/bin/activate
        pytest --version

    - name: Wait for Render deployment to complete (2 minutes)
      run: sleep 120

    - name: Run Selenium tests
      run: |
        source .venv/bin/activate
        pytest tests/selenium_script.py --maxfail=1 --disable-warnings -v
