name: Deploy and Run Tests Locally

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3  

    - name: Set up Python
      uses: actions/setup-python@v3  
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install -r requirements.txt

    - name: Verify Chrome and ChromeDriver paths
      run: |
        echo "Chrome is located at: $(which google-chrome)"
        google-chrome --version
        echo "ChromeDriver is located at: $(which chromedriver)"
        chromedriver --version

    - name: Set up Chrome and ChromeDriver
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: latest
        install-chromedriver: true

    - name: Make script executable
      run: chmod +x run_tests.sh

    - name: Run tests using script
      run: ./run_tests.sh
